### ISSUE TITLE
Enhance to allow use of any SPI controller on Teensy

### ISSUE THREAD

**Issue by jrw429** [sparkfun/TeensyView#4]
This library is hardcoded to use the first SPI interface on the Teensy. The Teensy can have up to three SPI interfaces. The SPI library for the Teensy will instantiate three instances of the SPIClass if the processor supports it. These objects are called SPI, SPI1 and SPI2. I would like to request an enhancement so that it is possible to specify which SPI interface (which SPIClass object) to use. Optionally passing in the SPIClass object would be one way to do this.

**Comment by oclyke** [comment]
Great idea! Check out pull request #6 and let me know if it does what you want. If you can, please test it and let me know if there are any bugs. If there's still a problem then go ahead and re-open this issue.
